<a href="https://colab.research.google.com/github/gauriiii13/ML-Models/blob/main/Heart_Disease_Prediction_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Importing the Dependencies**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#**Data Collection and Processing**

In [ ]:
#loading csv file into pandas dataframe
heart_df=pd.read_csv('/content/heart.csv')

In [ ]:
#print 1st 5 rows of dataframe
heart_df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
#checking the number of rows and columns in dataset
heart_df.shape

(1025, 14)

Our dataset contains 1025 rows and 14 columns

In [ ]:
#getting info on data
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


All of the columns except column 9 'oldpeak' has data type int64, oldpeak has data type float64

In [ ]:
#checking for missing values
heart_df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

Our data has no missing values in any column

In [ ]:
#statistical measures of the data
heart_df.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [ ]:
#checking the distribution of target values
heart_df['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

1 --> diseased heart
0 --> healthy heart
We can see that the distribution of data among diseased and healthy heart is very even, so we dont need to do any processing on it.

#**Splitting the features and target**

In [ ]:
X= heart_df.drop(columns=['target'],axis=1)
Y=heart_df['target']
X=X.values

In [ ]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [ ]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64


#**Splitting the data into training data and test data**

In [ ]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(1025, 13) (820, 13) (205, 13)


Training data contains 80% of total data while test data contains 20% of total data

#**Model Training**

Logistic Regression model

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#**Model Evaluation**

Accuracy Score

In [ ]:
#accuracy on training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction, Y_train)

In [ ]:
print("Accuracy Score on Training Data:", training_data_accuracy)

Accuracy Score on Training Data: 0.8524390243902439


In [ ]:
#accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction, Y_test)

In [ ]:
print("Accuracy Score on Test Data:", test_data_accuracy)

Accuracy Score on Test Data: 0.8048780487804879


#**Building a Predictive System**

In [ ]:
input_data=(71,0,0,112,149,0,1,125,0,1.6,1,0,2)

#change input data into a numpy array
input_data_as_np_array= np.asarray(input_data)

#reshaping the np array to predict only for 1 value
input_data_reshaped=input_data_as_np_array.reshape(1,-1)

prediction=model.predict(input_data_reshaped)
print(prediction)

if prediction[0]==0:
  print("The person does not have heart disease")
else:
  print("The person has heart disease")

[1]
The person has heart disease


# **Saving the Trained Model**

In [ ]:
import pickle

In [ ]:
filename='trained_model1.sav'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
#loading the saved model
loaded_model=pickle.load(open('trained_model1.sav', 'rb'))

In [ ]:
input_data=(70,1,0,145,174,0,1,125,1,2.6,0,0,3)
#changing input data to numpy array
input_data_as_np_array=np.asarray(input_data)
#reshape to predict for 1 instance
input_data_reshaped=input_data_as_np_array.reshape(1,-1)
prediction=loaded_model.predict(input_data_reshaped)
print(prediction)

if prediction[0]== 0:
  print('The person does not have heart disease')
else:
  print('The person has heart disease')

[0]
The person does not have heart disease
